version: "3"

services:
  unicart:
    build: .
    environment:
      - SPRING_REDIS_HOST=redis
    ports:
      - 8080:8080
    depends_on:
      - redis
    links:
      - redis
    networks:
      - unicart-redis-net
  redis:
    image: "redis:6.2-alpine"
    ports:
      - 6379:6379
    networks:
      - unicart-redis-net
networks:
  unicart-redis-net:
    driver: bridge
